<?php

namespace App\Repositories;

use App\Helper;
use App\Models\Brand;

class BrandRepository extends BaseRepository
{
    public function getModel(): string
    {
        return Brand::class;
    }

    public function modifyResult($collection)
    {
        $collection = array_map(function ($item){
            $item['image'] = Helper::updatedImage($item['image']);
            return $item;
        }, $collection);
        return parent::modifyResult($collection); // TODO: Change the autogenerated stub
    }
}
