<?php

namespace App\Repositories;

use App\Helper;
use App\Models\Category;

class CategoryRepository extends BaseRepository
{
    protected $_relationships = ['products'];

    public function getModel(): string
    {
        return Category::class;
    }

    public function modifyResult($collection)
    {
        $collection = array_map(function($item){
            if(!is_array($item['products'])){
                return $item;
            }

            $item['products'] = array_map(function($subItem){
                $subItem['url_image'] = Helper::updatedImage($subItem['url_image']);
                return $subItem;
            }, $item['products']);

            return $item;
        }, $collection);
        return parent::modifyResult($collection); // TODO: Change the autogenerated stub
    }
}
